### ISSUE TITLE
Server crash leads to loss of inventory

### ISSUE THREAD

**Issue by computer-whisperer** [Danielv123/playerManager#2]
In the plugin's current state, cluster-wide player inventory only appears to update upon a clean player exit. If a player is on a server for a long period of time before it crashes, then the server will rollback to the last autosave while the player inventory reverts to the last clean exit. This can lead to loss of items (I lost six roboport mk3s to this).

If playerManager saves inventories periodically, as well as on player exit -- that would avoid this issue.

**Comment by Godmave** [comment]
this should be "solved" since inventory is saved to master once per minute

**Comment by Danielv123** [comment]
That is an acceptable solution.
