### ISSUE TITLE
Inventory dump with PowerArmor on login

### ISSUE THREAD

**Issue by computer-whisperer** [Danielv123/playerManager#3]
If a player has a mostly-full inventory that has been expanded by PowerArmor, the items in those extra inventory slots get duplicated and dumped on the ground on login.

I have seen this bug from three different players on three different worlds in one clusterio cluster.

Video example: https://youtu.be/U8VmGQ4_jBY

Mod list:
 angelsaddons-warehouses_0.3.0.zip   angelssmelting_0.4.6.zip        bobelectronics_0.16.0.zip   boblogistics_0.16.23.zip   bobpower_0.16.8.zip     botbuzz_1.0.2.zip                 FNEI_0.1.9.zip                        SeaBlockMetaPack_0.16.0.zip
 angelsbioprocessing_0.5.9.zip      'A Sea Block Config_0.2.4.zip'   bobenemies_0.16.0.zip       bobmining_0.16.0.zip       bobrevamp_0.16.3.zip    CircuitProcessing_0.1.2.zip       KS_Power_0.2.4.zip          'Nuclear Fuel_0.1.3.zip'           SpaceMod_0.3.12.zip
 angelspetrochem_0.7.12.zip          attach-notes_0.2.5.zip          bobinserters_0.16.8.zip     bobmodules_0.16.0.zip      bobtech_0.16.6.zip      clusterio_1.13.1.zip              LandfillPainting_0.2.4.zip   ScienceCostTweakerM_0.16.47.zip   textplates_0.3.3.zip
 angelsrefining_0.9.14.zip           bobassembly_0.16.1.zip          boblibrary_0.16.6.zip       bobplates_0.16.5.zip       bobwarfare_0.16.7.zip  'Explosive Excavation_1.1.4.zip'              SeaBlock_0.2.16.zip

**Comment by Danielv123** [comment]
This one is a simple fix. It starts by clearing all the slots, but it clears the armor slot before the main inventory which causes the spill.
